10. NumPy Array Iterating:

Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
If we iterate on a 1-D array it will go through each element one by one.

In [1]:
# 1-D Array
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [2]:
# 2-D Array
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
import numpy as np

arr = ([[1,2,3],[4,5,6]])

# Iterate down the scalar
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [4]:
# 3-D Array
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [5]:
import numpy as np

ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in ar:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Note1: Iterating Array using nditer():-

The function nditer() is a helping function that can be used from very basic to very advanced iterations.
It solves some basic issues which we face in iteration, lets go through it with examples.

In [6]:
import numpy as np

arr = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])

for x in np.nditer(arr):
    print(x)

1
2
4
5
6
7
8
9


In [7]:
import numpy as np

ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in np.nditer(ar):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


Note2: Enumerated Iteration Using ndenumerate():-

Enumeration means mentioning sequence number of somethings one by one.
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [8]:
import numpy as np

# 1-D
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
