11. Numpy Joining Array:

Joining means putting contents of two or more arrays in a single array.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [1]:
import numpy as np

# Adding two 1-D Array 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1, arr2))

print(arr3)

[1 2 3 4 5 6]


In [2]:
import numpy as np

# Adding two 2-D Array
arr4 = np.array([[4,5,6],[7,8,9]])
arr5 = np.array([[10,11,12],[13,14,15]])
arr6 = np.concatenate((arr4,arr5))

print(arr6)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Note: Joining Arrays Using Stack Functions:

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np

# hstack() to stack along rows 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [6]:
import numpy as np

# vstack() to stack along columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np

#dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
