2. Dimensions in Numpy Array:

A dimension in arrays is one level of array depth (nested arrays).
Nested array: are arrays that have arrays as their elements.

In [1]:
# 0 Dimensional Array
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# These are the most common and basic arrays.

import numpy as np
arr0 = np.array(23)
print(arr0)

23


In [2]:
# 1 Dimensional Array
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# These are the most common and basic arrays.

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
# 2 Dimensional Array
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)

[[10 20 30]
 [40 50 60]]


In [4]:
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

import numpy as np
a = np.array(42) 
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
# Higher Dimensional Arrays
# An array can have any number of dimensions

e = np.array([1,2,3,4], ndmin=5)
print(e.ndim)

5


In [6]:
print(e)

[[[[[1 2 3 4]]]]]
