4. Slicing Array:

Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0.
If we don't pass end its considered length of array in that dimension.
If we don't pass step its considered 1.

In [1]:
#1-D Array
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:]) 
print(arr[:4])
print(arr[:4])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[1 2 3 4]
[2 4]
[1 3 5 7]


In [2]:
#2-D Array
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])   # Returns [7 8 9]
print(arr[0:2, 2])   # Returns [3 8]
print(arr[0:2, 1:4])     

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
