5. Data Type in Numpy:


i - integer,
b - boolean,
u - unsigned integer,
f - float,
c - complex float,
m - timedelta,
M - datetime,
O - object,
S - string,
U - unicode string,
V - fixed chunk of memory for other type ( void ).

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Returns Datatype of Given Numpy array
print(arr.dtype)

int32


In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

# Returns Datatype of Given Numpy array
print(arr.dtype)

<U6


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

# Returns Datatype of Given Numpy array
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [4]:
#Change the datatype from float to integer
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [5]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [6]:
import numpy as np

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
