8. NumPy Array Reshaping:

* Reshaping means changing the shape of an array.
* The shape of an array is the number of elements in each dimension.
* By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [1]:
import numpy as np

# Changing from 1-D to 2-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new = arr.reshape(4,3)

print(arr)
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np

# Changing from 1-D to 2-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
# Check if the returned array is a copy or a view:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)   # The example returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

# Note: We can not pass -1 to more than one dimension
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
