9. Flattening the arrays:

Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
new = arr.reshape(-1)

print(arr)
print(new)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
